//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Romanovich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int id { get; set; }
        public int IdSender { get; set; }
        public int IdReceiver { get; set; }
        public string Message { get; set; }
        public string Image { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
